My_second_Project/Login_app/urls.py
from django.conf.urls import url
from django.urls import path
from django.urls.resolvers import URLPattern
from Login_app import views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

app_name = 'Login_app'

urlpatterns = [
    path('', views.index, name= 'index'),
    path('register/', views.register, name= 'register'),
    path('login/', views.login_page, name= 'login'),
    path('user_login/', views.user_login, name= 'user_login'),
    path('logout/', views.user_logout, name= 'logout'),
    path('api/', views.api_request, name= 'api_name'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

My_second_Project/My_second_Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Login_app.urls')),
]

My_second_Project/Login_app/models.py
from django.db import models
from django.contrib.auth.models import User


class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    facebook_id = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to = 'profile_pics', blank =True)

    def __str__(self):
        return self.user.username

My_second_Project/Login_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.db import models
from Login_app.models import UserInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')

class UserInfoForm(forms.ModelForm):
    class Meta():
        model = UserInfo
        fields = ('facebook_id','profile_pic')

My_second_Project/Login_app/views.py
from Login_app.models import UserInfo
from django.shortcuts import render
from Login_app.forms import UserInfoForm,UserForm
from django.contrib.auth.models import User
import requests

# Create your views here.
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse, response
from django.urls import reverse


def login_page(request):
    return render(request,'Login_app/login.html',context={})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('Login_app:index'))
            else:
                return HttpResponse('Account is not active!')
        else:
            return HttpResponse('Login details are Wrong!!!')
    else:
        return HttpResponseRedirect(reverse('Login_app:login'))

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('Login_app:index'))

def index(request):
    dict = {}

    if request.user.is_authenticated:
        current_user = request.user
        user_id = current_user.id
        user_basic_info = User.objects.get(pk=user_id)
        user_more_info = UserInfo.objects.get(user__pk=user_id)

        dict = {'user_basic_info':user_basic_info,'user_more_info':user_more_info}
    return render(request, 'Login_app/index.html', context=dict)


def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        user_info_form = UserInfoForm(data=request.POST)

        if user_form.is_valid() and user_info_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            user_info = user_info_form.save(commit=False)
            user_info.user = user

            if 'profile_pic' in request.FILES:
                user_info.profile_pic = request.FILES['profile_pic']

            user_info.save()

            registered = True


    else:
        user_form = UserForm()
        user_info_form = UserInfoForm()
    dict = {'user_form':user_form,'user_info_form':user_info_form, 'registered': registered}
    return render(request, 'Login_app/register.html',context=dict)


def api_request(request):
    user_api = False
    if request.method == 'POST':
        username = request.POST.get('username')
        url = 'https://api.github.com/users/' + str(username)
        rspns = requests.get(url)
        user_api = rspns.json()
    return render(request,'Login_app/api.html', context={'user_api':user_api})

My_second_Project/templates/Login_app/api.html
{% extends 'Login_app/base.html' %}

{% block body_block %}

<form  method="POST" class="form-control fw-bolder border border-success border-2 rounded bg-secondary">
    {% csrf_token %}
<div class="text-center">
<input type="text" name="username" required>
<input type="submit" name="submit" value="GET GITHUB INFO" class="btn btn-success">
</div>

</form>
{% if user_api %}
<p>{{user_api.login}}</p>
<p>{{user_api.avatar_url}}</p>
<p>{{user_api.html_url}}</p>
{% endif %}
{% endblock %}

My_second_Project/templates/Login_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <title>{{ title }}</title>
</head>
<body>
        <nav class="navbar navbar-expand navbar-dark bg-dark sticky-top py-3 ">
            <div class="container-fluid">
      
              <div class="collapse navbar-collapse " id="navbarSupportedContent">
                <ul class="navbar-nav m-auto mb-2 mb-lg-0 ">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'Login_app:index' %}">HOME</a>
                  </li>
                  {% if user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'Login_app:logout' %}">LOGOUT</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'Login_app:api_name' %}">GET GITHUB INFO</a>
                  </li>
                  {% else %}
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'Login_app:register' %}">REGISTER</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'Login_app:login' %}">LOGIN</a>
                  </li>
                  {% endif %}
                </ul>
      
              </div>
            </div>
          </nav>

<div class="container" style="padding-top: 30px;">
  {% block body_block %}


  {% endblock %}
</div>

</body>
</html>

My_second_Project/templates/Login_app/index.html
{% extends 'Login_app/base.html' %}

{% block body_block %}
{% if user.is_authenticated %}
<p> Hi <h4>{{ user_basic_info.username }}!!! :)</p></h4>

<h6>Your email: {{ user_basic_info.email }}</h6>
<a href="{{ user_more_info.facebook_id }}">Facebook Profile</a><br> <br>
<p>Looking Good!!! <br><img src="/media/{{ user_more_info.profile_pic }}" width="600px"></p>
{% else %}
<div class="alert alert-primary">You are not logged in!!!</div>

{% endif %}
{% endblock %}

My_second_Project/templates/Login_app/login.html
{% extends 'Login_app/base.html' %}

{% block body_block %}

<form action="{% url 'Login_app:user_login' %}" method="POST" class="form-control fw-bolder border border-success border-2 rounded bg-secondary">
    {% csrf_token %}
    <div class="form-control fw-bolder border border-success border-2 rounded bg-secondary">
    <label for="username">Username</label>
    <input type="text" name="username" placeholder="Enter Your username" required class="form-control"><br>
    <label for="username">Password</label>
    <input type="password" name="password" placeholder="Enter Your password" required class="form-control"> <br>
    <input type="submit" name="submit" value="Login" class="btn btn-success btn-sm form-control">    
</div>
</form>

{% endblock %}

My_second_Project/templates/Login_app/register.html
{% extends 'Login_app/base.html' %}
{% load static %}

{% block body_block %}

{% if registered %}

<div class="alert alert-success"> Congratulation!!! Registration Successful!!!</div>

{% else %}

<form method ="POST" enctype="multipart/form-data" class="form-control fw-bolder border border-success border-2 rounded bg-secondary">
{% csrf_token %}
<div class="form-control fw-bolder border border-success border-2 rounded bg-secondary">
{{ user_form.as_p }}
{{ user_info_form.as_p }}
</div>
<input type="submit" name="submit" value="Register" class="btn btn-success form-control ">
</form>

{% endif %}

{% endblock %}